name: safeentry
description: Aplicativo para gerenciamento de entradas seguras
version: 1.0.0+1

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  # Estado, requisições, armazenamento
  flutter_bloc: ^9.1.1
  dio: ^5.3.3
  shared_preferences: ^2.2.2

  # Notificações e QR Code
  flutter_local_notifications: ^17.1.0
  qr_code_scanner: ^1.0.1
  qr_flutter: ^4.1.0
  permission_handler: ^10.4.0

  # Utilitários
  jwt_decoder: ^2.0.1
  flutter_svg: ^2.0.7
  google_fonts: ^6.1.0
  shimmer: ^3.0.0
  intl: ^0.20.2

  # Firebase
  firebase_core: ^2.14.0
  firebase_auth: ^4.6.3
  firebase_messaging: ^14.7.16
  cloud_firestore: ^4.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/icons/logo.svg
    - assets/icons/google.png
